
package maison.d.hote;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

/**
 *
 * @author ACH
 */
public class Homepage extends javax.swing.JFrame {
    Cl cl;
    Rooms rm;
    In chin;
    /**
     * Creates new form NewJFrame
     */
    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inbutton = new javax.swing.JButton();
        Customerlist = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Roomsbutton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HomePage");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
	setUndecorated(true);
        setLocationByPlatform(true);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 100));

        inbutton.setBackground(new java.awt.Color(0, 0, 0));
        inbutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inbutton.setForeground(new java.awt.Color(255, 255, 255));
        inbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3284680.png"))); // NOI18N
        inbutton.setText("        Check in/out");
        inbutton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inbutton.setMargin(new java.awt.Insets(2, 30, 2, 14));
        inbutton.setPreferredSize(new java.awt.Dimension(151, 90));
        inbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inbuttonActionPerformed(evt);
            }
        });

        Customerlist.setBackground(new java.awt.Color(0, 0, 0));
        Customerlist.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Customerlist.setForeground(new java.awt.Color(255, 255, 255));
        Customerlist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/target.png"))); // NOI18N
        Customerlist.setText("        Customerlist");
        Customerlist.setBorderPainted(false);
        Customerlist.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Customerlist.setMargin(new java.awt.Insets(2, 30, 2, 14));
        Customerlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerlistActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(0, 0, 0));
        Logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-out.png"))); // NOI18N
        Logout.setText("             Logout");
        Logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Logout.setMargin(new java.awt.Insets(2, 30, 2, 14));
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(0, 0, 0));
        Exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit (1).png"))); // NOI18N
        Exit.setText("               Exit");
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Exit.setMargin(new java.awt.Insets(2, 30, 2, 14));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Roomsbutton1.setBackground(new java.awt.Color(0, 0, 0));
        Roomsbutton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Roomsbutton1.setForeground(new java.awt.Color(255, 255, 255));
        Roomsbutton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bed (2).png"))); // NOI18N
        Roomsbutton1.setText("           ROOMS");
        Roomsbutton1.setActionCommand("       Rooms");
        Roomsbutton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Roomsbutton1.setMargin(new java.awt.Insets(2, 30, 2, 14));
        Roomsbutton1.setVerifyInputWhenFocusTarget(false);
        Roomsbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Roomsbutton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Customerlist, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Roomsbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(Roomsbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Customerlist, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );

        Roomsbutton1.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 1080));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgfhh.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));
    }// </editor-fold>//GEN-END:initComponents

    private void Roomsbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Roomsbutton1ActionPerformed
       rm=new Rooms();
       rm.setVisible(true);
//       if(cl.isShowing())
//       cl.dispose();
//       else
//       chin.dispose();
    }//GEN-LAST:event_Roomsbutton1ActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        int check=JOptionPane.showConfirmDialog(null, "This action will terminate the applcation,are you sure?","Exit Confirmation",JOptionPane.YES_NO_OPTION);
        if(check==0){
        System.exit(0);
        }
    }//GEN-LAST:event_ExitActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        int check=JOptionPane.showConfirmDialog(null, "Do you want to logout?","Logout Confirmation",JOptionPane.YES_NO_OPTION);
        if(check==0){
                    try{
        rm.dispose();
        cl.dispose();
        chin.dispose();
            }
            catch(Exception e){}
        setVisible(false);
        new Login().setVisible(true);
        }
    }//GEN-LAST:event_LogoutActionPerformed

    private void inbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inbuttonActionPerformed
        chin=new In();
        chin.setVisible(true);
        if(rm.isShowing())
        rm.dispose();
        else
        cl.dispose();
    }//GEN-LAST:event_inbuttonActionPerformed

    private void CustomerlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerlistActionPerformed
        cl=new Cl();
        cl.setVisible(true);
        if(rm.isShowing())
        rm.dispose(); 
      else
        chin.dispose();
        
    }//GEN-LAST:event_CustomerlistActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       int check=JOptionPane.showConfirmDialog(null, "This action will terminate the applcation,are you sure?","Exit Confirmation",JOptionPane.YES_NO_OPTION);
        if(check==0){
        System.exit(0);
        }
        else {
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Homepage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Customerlist;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Roomsbutton1;
    private javax.swing.JButton inbutton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
