
package maison.d.hote;
public class Login extends javax.swing.JFrame {

    
     
    public Login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constAructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginpasswordinput = new javax.swing.JPasswordField();
        loginusernameinpute = new javax.swing.JTextField();
        loginusername = new javax.swing.JLabel();
        loginpassword = new javax.swing.JLabel();
        loginbutton = new javax.swing.JButton();
        loginwarning = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login page");
        setPreferredSize(new java.awt.Dimension(1020, 600));
        getContentPane().setLayout(null);

        loginpasswordinput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loginpasswordinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginpasswordinputActionPerformed(evt);
            }
        });
        getContentPane().add(loginpasswordinput);
        loginpasswordinput.setBounds(680, 360, 203, 28);

        loginusernameinpute.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(loginusernameinpute);
        loginusernameinpute.setBounds(680, 290, 203, 28);

        loginusername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loginusername.setText("Username");
        getContentPane().add(loginusername);
        loginusername.setBounds(540, 290, 78, 22);

        loginpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loginpassword.setText("Password");
        getContentPane().add(loginpassword);
        loginpassword.setBounds(540, 360, 74, 22);

        loginbutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loginbutton.setText("Login");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(loginbutton);
        loginbutton.setBounds(750, 410, 133, 40);

        loginwarning.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginwarning.setForeground(new java.awt.Color(255, 0, 51));
        loginwarning.setText("       ");
        getContentPane().add(loginwarning);
        loginwarning.setBounds(540, 500, 340, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user (1).png"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(620, 20, 150, 150);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(1020, 800));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204, 100));
        jPanel1.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hh.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 20, 310, 110);

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 600));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("WELCOME TO LOGIN PAGE");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/light-blue-background (1).jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1020, 600);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(690, 100, 41, 16);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginpasswordinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginpasswordinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginpasswordinputActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        String username=loginusernameinpute.getText();
        String password=loginpasswordinput.getText();
        if(username.equals("A") && password.equals("A")){
            loginwarning.setText(" ");
        setVisible(false);
        Homepage H=new Homepage();
        H.setVisible(true);
        H.setExtendedState(H.MAXIMIZED_BOTH);

        }
        else if (username.equals("") || password.equals("")){
             loginwarning.setText("Please fill empty inputs");
        }
        else
            loginwarning.setText("Incorrect Username/password");
        
    }//GEN-LAST:event_loginbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginbutton;
    private javax.swing.JLabel loginpassword;
    private javax.swing.JPasswordField loginpasswordinput;
    private javax.swing.JLabel loginusername;
    private javax.swing.JTextField loginusernameinpute;
    private javax.swing.JLabel loginwarning;
    // End of variables declaration//GEN-END:variables
}
