/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maison.d.hote;

import DB.DBmgmt;
import DB.Operations;

import java.sql.ResultSet;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import DB.Select;
import java.awt.Color;
import java.sql.Connection;
import java.sql.Statement;
/**
 *
 * @author ACH
 */
public class Rooms extends javax.swing.JFrame {

    /**
     * Creates new form Rooms
     */
    public Rooms() {
        initComponents();
            combobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Unusedbutton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Rmtable = new javax.swing.JTable();
        Deleteroom = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Addroombutton = new javax.swing.JButton();
        Roomprice = new javax.swing.JTextField();
        RoomType1 = new javax.swing.JComboBox<>();
        RoomNumberinput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Roomnumberupdate = new javax.swing.JComboBox<>();
        roompriceupdate = new javax.swing.JTextField();
        roomstatusupdate = new javax.swing.JComboBox<>();
        Updateroom = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
	setUndecorated(true);
        setBackground(new Color(0.1f,0.1f,0.1f,0.7f));
        setLocation(new java.awt.Point(420, 150));
        setPreferredSize(new java.awt.Dimension(1450, 750));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Unusedbutton3.setBackground(new java.awt.Color(0, 0, 0));
        Unusedbutton3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Unusedbutton3.setForeground(new java.awt.Color(255, 255, 255));
        Unusedbutton3.setText("Rooms");
        Unusedbutton3.setBorderPainted(false);
        Unusedbutton3.setContentAreaFilled(false);
        Unusedbutton3.setDefaultCapable(false);
        Unusedbutton3.setEnabled(false);
        Unusedbutton3.setFocusPainted(false);
        Unusedbutton3.setFocusable(false);
        Unusedbutton3.setRequestFocusEnabled(false);
        Unusedbutton3.setRolloverEnabled(false);
        Unusedbutton3.setSelected(true);
        Unusedbutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Unusedbutton3ActionPerformed(evt);
            }
        });
        getContentPane().add(Unusedbutton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1430, 149));

        Rmtable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Rmtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Room Number", "Room Type", "Room Price", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Rmtable);
        if (Rmtable.getColumnModel().getColumnCount() > 0) {
            Rmtable.getColumnModel().getColumn(0).setMaxWidth(150);
            Rmtable.getColumnModel().getColumn(1).setResizable(false);
            Rmtable.getColumnModel().getColumn(2).setResizable(false);
            Rmtable.getColumnModel().getColumn(3).setResizable(false);
            Rmtable.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 192, 570, 442));

        Deleteroom.setBackground(new java.awt.Color(0, 0, 0));
        Deleteroom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Deleteroom.setForeground(new java.awt.Color(255, 255, 255));
        Deleteroom.setText("Delete Room");
        Deleteroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteroomActionPerformed(evt);
            }
        });
        getContentPane().add(Deleteroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 650, -1, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Room Number");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 150, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Room Type");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 130, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Room Price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 130, 40));

        Addroombutton.setBackground(new java.awt.Color(0, 0, 0));
        Addroombutton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Addroombutton.setForeground(new java.awt.Color(255, 255, 255));
        Addroombutton.setText("Add Room");
        Addroombutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddroombuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Addroombutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, 150, 40));

        Roomprice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(Roomprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 180, 40));

        RoomType1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RoomType1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double Bed", "Duplex" }));
        RoomType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomType1ActionPerformed(evt);
            }
        });
        getContentPane().add(RoomType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, 180, 40));

        RoomNumberinput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(RoomNumberinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, 180, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Room Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 290, 150, 40));

        Roomnumberupdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Roomnumberupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomnumberupdateActionPerformed(evt);
            }
        });
        getContentPane().add(Roomnumberupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 290, 180, 40));

        roompriceupdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roompriceupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roompriceupdateActionPerformed(evt);
            }
        });
        getContentPane().add(roompriceupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 350, 180, 40));

        roomstatusupdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        roomstatusupdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Not available" }));
        getContentPane().add(roomstatusupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 410, 180, 40));

        Updateroom.setBackground(new java.awt.Color(0, 0, 0));
        Updateroom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Updateroom.setForeground(new java.awt.Color(255, 255, 255));
        Updateroom.setText("Update Room");
        Updateroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateroomActionPerformed(evt);
            }
        });
        getContentPane().add(Updateroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 490, -1, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Status");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 410, 90, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Room Price");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 350, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddroombuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddroombuttonActionPerformed
        String room_number=RoomNumberinput.getText();
        String type=(String)RoomType1.getSelectedItem();
        String price=Roomprice.getText();
//        String Status=(String)status.getSelectedItem();
        String Query="insert into ROOMS(id,room_number,type,price,status) values(inc.nextval,'"+room_number+"','"+type+"','"+price+"','avialable')";
        Operations.DATA(Query,"Room Added Successfully");
        setVisible(false);
        new Rooms().setVisible(true);
        
    }//GEN-LAST:event_AddroombuttonActionPerformed

    private void roompriceupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roompriceupdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roompriceupdateActionPerformed

    private void UpdateroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateroomActionPerformed
        // TODO add your handling code here:
        String newroom_number=(String)Roomnumberupdate.getSelectedItem();
        String newprice=roompriceupdate.getText();
        String Status=(String)roomstatusupdate.getSelectedItem();
        String Query="Update ROOMS set status='"+Status+"',Price='"+newprice+"' where room_number='"+newroom_number+"'";
        Operations.DATA(Query,"Room Updated Successfully");
        setVisible(false);
        new Rooms().setVisible(true);
    }//GEN-LAST:event_UpdateroomActionPerformed

    private void Unusedbutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Unusedbutton3ActionPerformed

    }//GEN-LAST:event_Unusedbutton3ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
    ResultSet rs=Select.getData("Select * from ROOMS Order by id");
    DefaultTableModel model=(DefaultTableModel)Rmtable.getModel();
     try{ 
     while(rs.next())
     {
          model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)});
     }
     rs.close();
     }
     catch(Exception e){JOptionPane.showMessageDialog(null,e);}
    }//GEN-LAST:event_formComponentShown

    private void RoomType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomType1ActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void RoomnumberupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomnumberupdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RoomnumberupdateActionPerformed

    private void DeleteroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteroomActionPerformed
        int row =Rmtable.getSelectedRow();
        String target=Rmtable.getModel().getValueAt(row,0).toString();
        String Query="DELETE FROM ROOMS where id="+target;
        Operations.DATA(Query,"Room Deleted Successfully");
        setVisible(false);
        new Rooms().setVisible(true);
    }//GEN-LAST:event_DeleteroomActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Rooms().setVisible(true);
//            }
//        });
//    }
        private void combobox(){
        Connection con= null;
        Statement st=null;
            try{
          ResultSet rs=Select.getData("Select * from ROOMS Order by room_number");
        while(rs.next())
        {
          String numb=rs.getString("room_number");
          Roomnumberupdate.addItem(numb);
        }
     rs.close();
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addroombutton;
    private javax.swing.JButton Deleteroom;
    private javax.swing.JTable Rmtable;
    private javax.swing.JTextField RoomNumberinput;
    private javax.swing.JComboBox<String> RoomType1;
    private javax.swing.JComboBox<String> Roomnumberupdate;
    private javax.swing.JTextField Roomprice;
    private javax.swing.JButton Unusedbutton3;
    private javax.swing.JButton Updateroom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField roompriceupdate;
    private javax.swing.JComboBox<String> roomstatusupdate;
    // End of variables declaration//GEN-END:variables
}
